2025-02-14 09:35:48 [twisted] CRITICAL: Unhandled error in Deferred:
2025-02-14 09:35:48 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 152, in crawl
    self.engine = self._create_engine()
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 166, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/core/engine.py", line 101, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 109, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/utils/misc.py", line 71, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scrapy_user_agents'
2025-02-14 09:37:54 [twisted] CRITICAL: Unhandled error in Deferred:
2025-02-14 09:37:54 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 152, in crawl
    self.engine = self._create_engine()
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 166, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/core/engine.py", line 101, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 109, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/utils/misc.py", line 71, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scrapy_user_agents'
2025-02-14 09:39:37 [twisted] CRITICAL: Unhandled error in Deferred:
2025-02-14 09:39:37 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 152, in crawl
    self.engine = self._create_engine()
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 166, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/core/engine.py", line 101, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 109, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 77, in from_crawler
    return cls._from_settings(crawler.settings, crawler)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 86, in _from_settings
    mwcls = load_object(clspath)
  File "/home/devops/Desktop/Kiama/Python/data_scrapping/venv/lib/python3.10/site-packages/scrapy/utils/misc.py", line 71, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scrapy_user_agents'
